package com.github.kjetilv.statiktalk

internal val senderTemplate
    get() =
        """
package 〔packidge〕

import com.github.kjetilv.statiktalk.api.SendMediatorBase

import 〔sourcePackidge〕.〔service〕

import no.nav.helse.rapids_rivers.RapidsConnection

/*
  This file was generated by statiktalk.  Changes will be reverted when you build again.
*/

fun RapidsConnection.〔serviceCc〕(): 〔service〕 =
    〔service〕SendMediator(this)

private class 〔service〕SendMediator(
    rapidsConnection: RapidsConnection
) : SendMediatorBase(rapidsConnection), 〔service〕 {

    override fun 〔serviceName〕(
〔parameters:{parameter|
        〔parameter〕: String,
        }〕〔if(contextual)
        〕        context: 〔contextClass〕〔if(contextualNonNull)〕〔else〕?〔endif〕
        〔else〕〔endif〕
    ) {
        send〔if(contextualNonNull)〕1〔else〕0〔endif〕(
            〔if(contextual)〕context〔else〕null〔endif〕,
            "@event_name" to "〔service〕_〔serviceName〕",
〔parameters:{parameter|
            "〔parameter〕" to 〔parameter〕,
            }
〕       )
    }
}
""".trimIndent()
